#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug  7 19:56:43 2019

@author: ee524
"""

import numpy as np
a = np.array([[1,1,1],[1,0,0],[1,0,1]])
Y = np.array([[1,1,1,1,1,1,1,1,1]]).T
A = np.zeros([9,9])
u = [0,0,0,1,1,1,2,2,2]
for i,k in zip(range(9), u):
    if(i%3 == 0):
        j = 0
    print(j)
    A[i:i+1,j:j+3] = a[k]
    print(a[k])
    j += 3
t=np.dot(np.transpose(A),A)
ahash= np.dot(np.linalg.inv(t),np.transpose(A))
p=np.dot(ahash,Y)
P = p.reshape(3,3).T
U, S, VT = np.linalg.svd(P, full_matrices=True)